stages:
  train:
    cmd: python urbansound_classifier/train.py
    params:
      - transform
      - train
    deps:
      - data/UrbanSound8K
      - urbansound_classifier/model.py
      - urbansound_classifier/dataset.py
