data:
  annotations: data/UrbanSound8K/UrbanSound8K.csv
  audio_dir: data/UrbanSound8K

transform:
  type: mel_spectrogram
  params:
  # audio params
    sample_rate: 22050
    duration: 1
  # spectrogram params
    n_fft: 1024
    hop_length: 512
    # mel spectrogram params
    n_mels: 64
    # mfcc params
    n_mfcc: 40

train:
  epochs: 10
  batch_size: 32
  shuffle: True
  lr: 0.001