transform:
  type: mel_spectrogram
  params:
  # audio params
    sample_rate: 16000
    duration: 1
  # spectrogram params
    n_fft: 2048
    hop_length: 512
    # mel spectrogram params
    n_mels: 128
    # mfcc params
    n_mfcc: 40

train:
  epochs: 10
  batch_size: 32
  shuffle: True
  lr: 0.001